### ISSUE TITLE
Missing a namespace?

### ISSUE THREAD

**Issue by varguiniano** [neurodigitaltechnologies/UnitySDK#2]
Hi,

I'm not sure if I should be asking this here, but I don't know anywhere else to ask to be honest. I created a Unity project (on Unity 2017.3.1f1) with this SDK, the SteamVR plugin and the package mentioned [here](http://docs.neurodigital.es/#/unity/Link_hands_to_vive_trackers). When adding this last package, Unity complains about missing the namespace NDAPIIMC.

![Imagen](https://user-images.githubusercontent.com/3752289/37141390-1a04340a-22b5-11e8-94bf-ac6c17d98e30.png)

I've tried importing every namespace in the dlls and even added the one from the C# SDK, but I can't find the classes missing anywhere (even when they appear in the [docs](http://docs.neurodigital.es/#/unity/api.html)) so I'm pretty lost right now. What am I missing?

Thanks in advance.

**Comment by PinoNeurodigital** [comment]
Hello @varguiniano,

If you're using our **SteamUtilities** package, you should use the **UnitySDK v3** (you can download it [here](https://github.com/neurodigitaltechnologies/UnitySDK/releases/tag/v3)).  The problem is that the new version does not have a class called _HandMotionController_. We are still working on new version functionalities as well as compatibility with the SteamVR plugin.

We apologize for the inconveniences.

**Comment by varguiniano** [comment]
Hi,

thanks for the help. It now finds all the required classes.
